"""Build the bounded exact-head v0.23.1 review manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess

BASE_MAIN = "b08b9c3df74ef6a23046be396289e2fd72dc336b"
EVIDENCE = "docs/evidence/vfx-asset-family-runtime-v0231"


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(); parser.add_argument("--output-dir", required=True); parser.add_argument("--repository-root", default="."); parser.add_argument("--base-ref", required=True); parser.add_argument("--head-ref", required=True); parser.add_argument("--head-branch", required=True); parser.add_argument("--pr-number", required=True, type=int); parser.add_argument("--tests-json", required=True); parser.add_argument("--validation-json", required=True); parser.add_argument("--gates-json", required=True); parser.add_argument("--controls-json", required=True); parser.add_argument("--determinism-json", required=True); parser.add_argument("--production-json", required=True); args = parser.parse_args(); root = Path(args.repository_root).resolve(); state = load(root / "docs/evidence/current-state.json"); gates = load(Path(args.gates_json)); controls = load(Path(args.controls_json)); det = load(Path(args.determinism_json)); prod = load(Path(args.production_json)); execution = load(root / f"{EVIDENCE}/execution-evidence-v0231.json")
    changed = [line for line in subprocess.run(["git", "diff", "--name-only", f"{args.base_ref}..{args.head_ref}"], cwd=root, capture_output=True, text=True, check=False).stdout.splitlines() if line]
    names = ("vfx-family-manifest-v0231.json", "effect-class-contract-v0231.json", "lifecycle-timing-v0231.json", "blend-alpha-contract-v0231.json", "alpha-decoded-v0231.json", "spatial-anchor-contract-v0231.json", "budget-authority-v0231.json", "fallback-degradation-v0231.json", "representation-import-v0231.json", "integration-linkage-v0231.json", "cache-provenance-v0231.json", "hard-gates-v0231.json", "negative-controls-v0231.json", "full-slice-two-run-determinism-v0231.json", "production-registry-v0231.json", "test-only-fixture-manifest-v0231.json", "execution-evidence-v0231.json", "historical-immutability-v0231.json", "capability-matrix-validation-v0231.json", "state-consistency-v0231.json", "schema-validation-v0231.json", "v0.23.0-rejection-correction-v0231.json", "exact-sha-lifecycle-v0231.json", "qa-contact-timing-v0231.json", "vfx-effect-contact-sheet-v0231.png", "vfx-timing-qa-sheet-v0231.png", "vfx-budget-fallback-qa-sheet-v0231.png"); evidence = {name.rsplit(".", 1)[0]: f"{EVIDENCE}/{name}" for name in names}; overall = execution.get("overall_pass") is True and det.get("status") == "PASS" and prod.get("registry") == [] and len(gates.get("gates", {})) == 32 and all(item.get("status") == "PASS" and type(item.get("observed")) is bool and item.get("observed") is True for item in gates.get("gates", {}).values()) and len(controls.get("controls", {})) == 30 and all(item.get("status") == "PASS" and item.get("result") == "REJECT" and item.get("expected_rejection_class") == item.get("observed_rejection_class") for item in controls.get("controls", {}).values())
    value = {"schema_version": "0.23.1", "manifest_type": "github-ci-vfx-asset-family-v0231-review", "repository": {"name": "KayzenRoot/ugas", "url": "https://github.com/KayzenRoot/ugas", "default_branch": "main"}, "pull_request": {"number": args.pr_number, "base_sha": args.base_ref, "head_sha": args.head_ref, "merge_base_sha": args.base_ref, "head_branch": args.head_branch, "base_branch": "main"}, "scope": {"version": "0.23.1", "phase": "VFX_ASSET_FAMILY", "current_gate": "VFX_ASSET_FAMILY_RUNTIME_CORRECTION_F22_F28_TECHNICALLY_QUALIFIED_EXTERNAL_REVIEW_REQUIRED", "baseline_main_sha": BASE_MAIN, "allowed_next_actions": ["external_review_vfx_asset_family_v0231"], "next_candidate": "ORCHESTRATION_RUNTIME_HARDENING", "new_generation": 0, "corrections": ["F-22", "F-23", "F-24", "F-25", "F-26", "F-27", "F-28"]}, "changed_files": changed, "change_statistics": {"files": len(changed)}, "current_state": {"path": "docs/evidence/current-state.json", "version": state.get("version"), "phase": state.get("phase"), "current_gate": state.get("current_gate"), "tracked_head_sha": state.get("review", {}).get("head_sha"), "head_sha_source": state.get("review", {}).get("head_sha_source"), "production_approved": state.get("production_approved"), "production_routing": state.get("production_routing"), "allowed_next_actions": state.get("allowed_next_actions")}, "tests": load(Path(args.tests_json)), "validation": load(Path(args.validation_json)), "gates": gates.get("gates", {}), "negative_controls": controls, "determinism": det, "vfx_evidence": evidence, "historical_authority": {"v0230_reviewed_head": "c8967f5f7b4d3f66b402d10ae8fe5f29cb9fbb72", "v0230_evidence_immutable": True, "base_main_sha": BASE_MAIN, "no_approved_authority_rewritten": True}, "production_boundary": {"approved": False, "routing": "BLOCKED", "new_generation": 0, "real_vfx_asset_coverage": "NONE", "synthetic_vfx_fixture": "TEST_ONLY", "production_registry_empty": prod.get("registry") == []}, "review_boundary": {"external_review_required": True, "do_not_merge": True, "merge_authorization": "NOT_AUTHORIZED_UNTIL_SOL_APPROVAL", "pr_open_required": True, "pr_merged": False, "ui_started": False, "orchestration_started": False, "production_art_started": False, "provider_generation_started": False}, "security_boundary": {"secrets_included": False, "model_weights_included": False, "telemetry_db_included": False, "local_credentials_included": False}, "overall_status": "PASS" if overall else "FAIL"}
    output = Path(args.output_dir); output.mkdir(parents=True, exist_ok=True); (output / "github-review-manifest-v0231.json").write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"); print(json.dumps({"status": "V0231_GITHUB_REVIEW_MANIFEST_BUILT", "head_sha": args.head_ref, "pr_number": args.pr_number})); return 0


if __name__ == "__main__":
    raise SystemExit(main())
