"""Build the bounded exact-head v0.23.2 review manifest."""
from __future__ import annotations
import argparse, json, subprocess
from pathlib import Path
BASE_MAIN = "b08b9c3df74ef6a23046be396289e2fd72dc336b"; EVIDENCE = "docs/evidence/vfx-asset-family-runtime-v0232"
def load(path: Path) -> dict: return json.loads(path.read_text(encoding="utf-8"))
def main() -> int:
    p=argparse.ArgumentParser(); p.add_argument("--output-dir",required=True); p.add_argument("--repository-root",default="."); p.add_argument("--base-ref",required=True); p.add_argument("--head-ref",required=True); p.add_argument("--head-branch",required=True); p.add_argument("--pr-number",required=True,type=int); p.add_argument("--tests-json",required=True); p.add_argument("--validation-json",required=True); p.add_argument("--gates-json",required=True); p.add_argument("--controls-json",required=True); p.add_argument("--determinism-json",required=True); p.add_argument("--production-json",required=True); a=p.parse_args(); root=Path(a.repository_root).resolve(); state=load(root/"docs/evidence/current-state.json"); gates=load(Path(a.gates_json)); controls=load(Path(a.controls_json)); det=load(Path(a.determinism_json)); prod=load(Path(a.production_json)); execution=load(root/f"{EVIDENCE}/execution-evidence-v0232.json")
    changed=[x for x in subprocess.run(["git","diff","--name-only",f"{a.base_ref}..{a.head_ref}"],cwd=root,capture_output=True,text=True,check=False).stdout.splitlines() if x]
    names=("vfx-family-manifest-v0232.json","effect-class-contract-v0232.json","lifecycle-timing-v0232.json","blend-alpha-contract-v0232.json","alpha-decoded-v0232.json","spatial-anchor-contract-v0232.json","budget-authority-v0232.json","fallback-degradation-v0232.json","representation-import-v0232.json","integration-linkage-v0232.json","cache-provenance-v0232.json","fallback-output-proof-v0232.json","hard-gates-v0232.json","negative-controls-v0232.json","full-slice-two-run-determinism-v0232.json","degraded-output-determinism-v0232.json","production-registry-v0232.json","test-only-fixture-manifest-v0232.json","execution-evidence-v0232.json","historical-immutability-v0232.json","capability-matrix-validation-v0232.json","state-consistency-v0232.json","schema-validation-v0232.json","v0.23.1-rejection-correction-v0232.json","exact-sha-lifecycle-v0232.json","qa-contact-timing-v0232.json","vfx-effect-contact-sheet-v0232.png","vfx-timing-qa-sheet-v0232.png","vfx-budget-fallback-qa-sheet-v0232.png"); evidence={n.rsplit(".",1)[0]:f"{EVIDENCE}/{n}" for n in names}
    overall=execution.get("overall_pass") is True and det.get("status")=="PASS" and prod.get("registry")==[] and len(gates.get("gates",{}))==32 and all(x.get("status")=="PASS" and type(x.get("observed")) is bool and x.get("observed") is True for x in gates.get("gates",{}).values()) and len(controls.get("controls",{}))==18 and all(x.get("status")=="PASS" and x.get("result")=="REJECT" and x.get("expected_rejection_class")==x.get("observed_rejection_class") for x in controls.get("controls",{}).values())
    value={"schema_version":"0.23.2","manifest_type":"github-ci-vfx-asset-family-v0232-review","repository":{"name":"KayzenRoot/ugas","url":"https://github.com/KayzenRoot/ugas","default_branch":"main"},"pull_request":{"number":a.pr_number,"base_sha":a.base_ref,"head_sha":a.head_ref,"merge_base_sha":a.base_ref,"head_branch":a.head_branch,"base_branch":"main"},"scope":{"version":"0.23.2","phase":"VFX_ASSET_FAMILY","current_gate":"VFX_ASSET_FAMILY_RUNTIME_CORRECTION_F23R_F26R_F27R_TECHNICALLY_QUALIFIED_EXTERNAL_REVIEW_REQUIRED","baseline_main_sha":BASE_MAIN,"allowed_next_actions":["external_review_vfx_asset_family_v0232"],"next_candidate":"ORCHESTRATION_RUNTIME_HARDENING","new_generation":0,"corrections":["F-23R","F-26R","F-27R"]},"changed_files":changed,"change_statistics":{"files":len(changed)},"current_state":{"path":"docs/evidence/current-state.json","version":state.get("version"),"phase":state.get("phase"),"current_gate":state.get("current_gate"),"tracked_head_sha":state.get("review",{}).get("head_sha"),"head_sha_source":state.get("review",{}).get("head_sha_source"),"production_approved":state.get("production_approved"),"production_routing":state.get("production_routing"),"allowed_next_actions":state.get("allowed_next_actions")},"tests":load(Path(a.tests_json)),"validation":load(Path(a.validation_json)),"gates":gates.get("gates",{}),"negative_controls":controls,"determinism":det,"vfx_evidence":evidence,"historical_authority":{"v0231_reviewed_head":"136079540f674c7467d93bd28e9834addbfce5c3","v0231_evidence_immutable":True,"v0230_evidence_immutable":True,"base_main_sha":BASE_MAIN,"no_approved_authority_rewritten":True},"production_boundary":{"approved":False,"routing":"BLOCKED","new_generation":0,"real_vfx_asset_coverage":"NONE","synthetic_vfx_fixture":"TEST_ONLY","production_registry_empty":prod.get("registry")==[]},"review_boundary":{"external_review_required":True,"do_not_merge":True,"merge_authorization":"NOT_AUTHORIZED_UNTIL_SOL_APPROVAL","pr_open_required":True,"pr_merged":False,"ui_started":False,"orchestration_started":False,"production_art_started":False,"provider_generation_started":False},"security_boundary":{"secrets_included":False,"model_weights_included":False,"telemetry_db_included":False,"local_credentials_included":False},"overall_status":"PASS" if overall else "FAIL"}
    out=Path(a.output_dir); out.mkdir(parents=True,exist_ok=True); (out/"github-review-manifest-v0232.json").write_text(json.dumps(value,indent=2,ensure_ascii=False)+"\n",encoding="utf-8"); print(json.dumps({"status":"V0232_GITHUB_REVIEW_MANIFEST_BUILT","head_sha":a.head_ref,"pr_number":a.pr_number})); return 0
if __name__ == "__main__": raise SystemExit(main())
